### PR TITLE
fix(text_input): support numpad keys

### LINKED ISSUE #702: BUG: numeric keypad no longer writes keys anymore
I can write numbers in text inputs while holding `shift + &` for example, but the keypad no longer works (since some time now)

### LINKED ISSUE #740: Num pad do not work with input fields
Hi,
My num pad doesn't work with the input fields (e.g. text input). Trying to turn num pad off and on doesn't help. 
I use latest Fedora, so there might be some incompatibility with the system maybe?

Edit: just want to add that the keys behave always as their alternative functions like arrows, insert, pg up, pg down etc..

### PR DESCRIPTION
**Pull request by mmstick**
Compared with the current iced implementation of text_input, and made changes based on that to get better character input support.

Closes #702 
Closes #740

### CODE REVIEW

File: src/widget/text_input/input.rs [hunk 1]
```diff
@@ -1579,7 +1580,18 @@ pub fn update<'a, Message: Clone + 'static>(
...
+            key,
+            modified_key,
+            text,
+            physical_key,
+            ..
+        }) => {
+            dbg!(&key);
+            dbg!(&modified_key);
+            dbg!(&physical_key);
+            dbg!(&text);
```
Comment (wash2) [inline src/widget/text_input/input.rs:1593]:
```suggestion
 ```

**Review by wash2 — CHANGES_REQUESTED** [review]

**Review by wash2 — APPROVED** [review]
